import type { Metadata } from "next";
import { Roboto, Raleway, Ubuntu } from "next/font/google";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import "bootstrap/dist/css/bootstrap.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "./globals.css";
import BootstrapClient from "@/client/BootstrapClient.js";

const ubuntu = Ubuntu({
  variable: "--font-nav",
  subsets: ["latin"],
  weight: "400",
});

const roboto = Roboto({
  variable: "--font-default",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-heading",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="main.js"></script>
      </head>
      <body
        className={`${ubuntu.variable} ${roboto.variable} ${raleway.variable} antialiased`}
      >
        <BootstrapClient />
        <Header />
        <main className="main">{children}</main>
        <Footer />

        {/* Scroll Top */}
        <a
          href="#"
          id="scroll-top"
          className="scroll-top d-flex align-items-center justify-content-center"
        >
          <i className="bi bi-arrow-up-short"></i>
        </a>
      </body>
    </html>
  );
}
