import type { Metadata } from "next";
import { Roboto, Raleway, Ubuntu } from "next/font/google";
import { UseAOS } from "@/hooks/UseAOS";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { ScrollTop } from "@/components/scroll-top";
import { PageTitle } from "@/components/page-title";
import BootstrapClient from "@/client/BootstrapClient.js";

import "bootstrap/dist/css/bootstrap.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "./globals.css";

const ubuntu = Ubuntu({
  variable: "--font-nav",
  subsets: ["latin"],
  weight: "400",
});

const roboto = Roboto({
  variable: "--font-default",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-heading",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tom's English",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.variable} ${roboto.variable} ${raleway.variable} antialiased`}
      >
        <BootstrapClient />
        <Header />
        <PageTitle />
        <main className="main">{children}</main>
        <Footer />

        {/* Scroll Animation Effect */}
        <UseAOS />

        {/* Scroll Top */}
        <ScrollTop />
      </body>
    </html>
  );
}
