import type { Metadata } from "next";
import { Roboto, Raleway, Ubuntu } from "next/font/google";
import { Header } from "@/components/header";
import 'bootstrap/dist/css/bootstrap.css';
import "bootstrap-icons/font/bootstrap-icons.css";
import "./globals.css";
import BootstrapClient from '@/client/BootstrapClient.js';

  
const ubuntu = Ubuntu({
  variable: "--font-nav",
  subsets: ["latin"],
  weight: "400"
});

const roboto = Roboto({
  variable: "--font-default",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-heading",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="main.js"></script>
      </head>
      <body
        className={`${ubuntu.variable} ${roboto.variable} ${raleway.variable} antialiased`}
      >
        <Header />
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
